// The map of the standard: which files load each pack, and which packs hold each chapter. Built from the
// packs themselves, so it cannot drift from them. It lands in two places: docs/rules.md for readers of the
// repo, and the end of core.md, because an installed session never sees docs/.
//   node scripts/rules-map.mjs [--check]
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { ROOT } from "./vendor-lib.mjs";
import { isRunDirectly } from "./files.mjs";

const RULES = join(ROOT, "kit", "rules", "tv");
const CORE = join(RULES, "core.md");
const DOC = join(ROOT, "docs", "rules.md");
const START = "<!-- rules-map:start (generated by scripts/rules-map.mjs) -->";
const END = "<!-- rules-map:end -->";
const PACK_ORDER = ["core", "typescript", "react", "accessibility", "styles", "scss", "testing", "node-tooling"];

const readPack = (name) => readFileSync(join(RULES, `${name}.md`), "utf8").replace(/\r\n/g, "\n");

const packsOnDisk = () => {
  const names = readdirSync(RULES).filter((f) => f.endsWith(".md")).map((f) => f.slice(0, -3));
  return [...PACK_ORDER.filter((n) => names.includes(n)), ...names.filter((n) => !PACK_ORDER.includes(n)).sort()];
};

const pathsOf = (text) => {
  const front = text.match(/^---\npaths:\n([\s\S]*?)\n---/);
  return front ? front[1].split("\n").map((line) => line.replace(/^\s*-\s*"?|"?\s*$/g, "")) : null;
};

// The chapter label every section heading carries, e.g. "## Casing (TV 02)".
const chaptersOf = (text) => [...text.matchAll(/^## .* \(((?:TV \d\d)|(?:identity: [a-z-]+)|AGENTS|README)\)$/gm)].map((m) => m[1]);

export const renderMap = () => {
  const packs = packsOnDisk();
  const chapters = new Map();
  for (const pack of packs) for (const label of chaptersOf(readPack(pack))) {
    if (!chapters.has(label)) chapters.set(label, new Set());
    chapters.get(label).add(pack);
  }
  const rank = (label) => (label.startsWith("TV ") ? `2${label}` : label.startsWith("identity") ? `1${label}` : `0${label}`);
  return [
    "| Pack | Loads when a file matching one of these is read |",
    "| --- | --- |",
    ...packs.map((pack) => {
      const paths = pathsOf(readPack(pack));
      return `| ${pack} | ${paths ? paths.map((p) => `\`${p}\``).join(", ") : "always"} |`;
    }),
    "",
    "| Chapter | Packs |",
    "| --- | --- |",
    ...[...chapters.keys()].sort((a, b) => rank(a).localeCompare(rank(b))).map((label) => `| ${label} | ${[...chapters.get(label)].join(", ")} |`)
  ].join("\n");
};

const renderDoc = (map) => [
  "# Rules",
  "",
  "TV-STANDARD installs as `~/.claude/rules/tv/`: a core that loads in every session, plus packs that",
  "load in full the first time a file matching their `paths:` is read. Creating a file does not load",
  "its pack, which is why the core says to read a matching file first. Generated by",
  "`scripts/rules-map.mjs` from the packs; the same map closes core.md. docs/coverage.md lists every",
  "section of the original standard and the pack it lives in.",
  "",
  "\"TV NN\" in a rule names the original chapter. Where a chapter is split, each section's heading",
  "carries the label, so a citation still finds its text.",
  "",
  map,
  ""
].join("\n");

const renderCore = (map) => {
  const core = readPack("core");
  const block = `${START}\n\n## Where each chapter lives\n\n${map}\n\n${END}`;
  return core.includes(START)
    ? core.replace(new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${END}`), block)
    : `${core.trimEnd()}\n\n---\n\n${block}\n`;
};

// Returns what is out of date; empty when both copies match the packs.
export const checkMap = () => {
  const map = renderMap();
  const problems = [];
  if (readFileSync(DOC, "utf8").replace(/\r\n/g, "\n") !== renderDoc(map)) problems.push("docs/rules.md is out of date; run node scripts/rules-map.mjs");
  if (readPack("core") !== renderCore(map)) problems.push("the map at the end of core.md is out of date; run node scripts/rules-map.mjs");
  return problems;
};

if (isRunDirectly(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const problems = checkMap();
    for (const problem of problems) console.log(`✖  ${problem}`);
    process.exit(problems.length ? 1 : 0);
  }
  const map = renderMap();
  writeFileSync(DOC, renderDoc(map));
  writeFileSync(CORE, renderCore(map));
  console.log("✔  docs/rules.md and the map in core.md written");
}
